// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdpH5nJraUX5-_AIxcYOVc5Ct3Hodf09U',
    appId: '1:838269444220:web:61b9c7c9f9b2ee24b529f9',
    messagingSenderId: '838269444220',
    projectId: 'badikwa-b3063',
    authDomain: 'badikwa-b3063.firebaseapp.com',
    storageBucket: 'badikwa-b3063.firebasestorage.app',
    measurementId: 'G-KLCVLP2VZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAY6am1jn1b4rRlT6Ok19AWOw8xSidAqE',
    appId: '1:838269444220:android:56a112422d6e1565b529f9',
    messagingSenderId: '838269444220',
    projectId: 'badikwa-b3063',
    storageBucket: 'badikwa-b3063.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaV4bkMXXGyKogesnDhfYCWaAeo-Q4K1I',
    appId: '1:838269444220:ios:0cda850ce1c32642b529f9',
    messagingSenderId: '838269444220',
    projectId: 'badikwa-b3063',
    storageBucket: 'badikwa-b3063.firebasestorage.app',
    iosBundleId: 'com.example.badikwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaV4bkMXXGyKogesnDhfYCWaAeo-Q4K1I',
    appId: '1:838269444220:ios:0cda850ce1c32642b529f9',
    messagingSenderId: '838269444220',
    projectId: 'badikwa-b3063',
    storageBucket: 'badikwa-b3063.firebasestorage.app',
    iosBundleId: 'com.example.badikwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdpH5nJraUX5-_AIxcYOVc5Ct3Hodf09U',
    appId: '1:838269444220:web:ea367e69d9a49e5bb529f9',
    messagingSenderId: '838269444220',
    projectId: 'badikwa-b3063',
    authDomain: 'badikwa-b3063.firebaseapp.com',
    storageBucket: 'badikwa-b3063.firebasestorage.app',
    measurementId: 'G-064W0BS9H7',
  );

}